data:
  train_data_dir: "./data/flower_dataset/train/"
  val_data_dir: "./data/flower_dataset/val/"
  test_data_dir: "./data/flower_dataset/test/"
  save_dir: "./results/flowers_predicts/"
  image_size: [128, 128]
  batch_size: 32

model:
  input_size: 3072
  hidden_size: 64
  num_classes: 3
  learning_rate: 0.001
  epochs: 1000

training:
  save_model: true
  model_save_path: "models/od_custom_flowers_model.h5"
  learning_rate: 0.01
  epochs: 128
  batch_size: 32